# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FaqFeature' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaqFeature
  pod 'Firebase/Firestore'
  target 'FaqFeatureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FaqFeatureUITests' do
    # Pods for testing
  end

end
